### ISSUE TITLE
Link to flattr missing in the downloads page

### ISSUE THREAD

**Issue by nicosomb** [vjousse/vim-for-humans-website#1]
When you click on Flattr icon, we only have "Make the payment & get your ebook". You should add the link to your flattr page.

**Comment by vjousse** [comment]
Interesting, I can't reproduce it using FF.
What browser are you using?

**Comment by nicosomb** [comment]
Oops, I reproduce it ... but it's due to the Ghostery addon. Sorry for the noise.
